import { searchSources } from './network-search';
import type { Category, Link, Resource } from './types';
import { providers } from './security';

export const e = (v: unknown) => String(v ?? '').replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]!));
const date = (v: string) => new Date(v).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai',month:'long',day:'numeric'});
const icons: Record<string,string> = {all:'▦',office:'▤',design:'◈',learning:'▧',tools:'⌘',ai:'✳'};
export const option = (value:string,label:string,current:string) => `<option value="${e(value)}" ${value===current?'selected':''}>${e(label)}</option>`;
export function layout(title: string, content: string, name: string, options: { admin?: boolean; local?: boolean; description?: string; canonical?: string; nav?: string; noindex?: boolean } = {}) {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(title)} · ${e(name)}</title><meta name="description" content="${e(options.description || '整理有用的资源，留给需要的时候。按分类浏览资料、模板和工具。')}">${options.noindex?'<meta name="robots" content="noindex,nofollow">':''}${options.canonical?`<link rel="canonical" href="${e(options.canonical)}">`:''}<link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><script defer src="/app.js"></script></head><body>
  <a class="skip" href="#main">跳转到正文</a><header class="site-header"><div class="header-inner"><a class="brand" href="/"><img src="/favicon.svg" width="34" height="34" alt=""><span>${e(name)}</span></a><nav aria-label="主导航">${options.admin?`<a href="/">浏览网站 ↗</a><span class="admin-indicator">${options.local?'本地预览':'管理后台'}</span>`:`<a class="${options.nav==='about'?'current':''}" href="/about">关于</a>`}</nav></div></header>
  ${options.admin?`<div class="admin-shell"><aside class="admin-sidebar"><span class="eyebrow">工作台</span><a href="/admin" class="${options.nav==='resources'?'selected':''}">▦ &nbsp; 资源管理</a><a href="/admin/categories" class="${options.nav==='categories'?'selected':''}">▤ &nbsp; 分类管理</a><a href="/admin/reports" class="${options.nav==='reports'?'selected':''}">⚑ &nbsp; 失效反馈</a><a href="/admin/requests" class="${options.nav==='requests'?'selected':''}">＋ &nbsp; 求资源</a><a href="/admin/stats" class="${options.nav==='stats'?'selected':''}">▥ &nbsp; 点击统计</a><a href="/admin/data" class="${options.nav==='data'?'selected':''}">⇅ &nbsp; 导入与备份</a><a href="/admin/settings" class="${options.nav==='settings'?'selected':''}">⚙ &nbsp; 网站设置</a><div class="sidebar-note">把好资源整理好，<br>让每一次寻找更轻松。</div></aside><main id="main" class="admin-main">${content}</main></div>`:`<main id="main" class="public-main">${content}</main>`}
  <footer class="simple-footer"><span>© ${new Date().getFullYear()} ${e(name)}</span></footer><div id="toast" role="status" aria-live="polite" hidden></div></body></html>`;
}
export function resourceCard(r: Resource) {
  const words = r.tags.split(',').filter(Boolean).slice(0,2);
  return `<article class="resource-card"><a class="card-art tone-${e(r.category_id||'tools')}" href="/r/${e(r.id)}" tabindex="-1" aria-hidden="true">${r.cover_key?`<img src="/media/${e(r.cover_key)}" alt="" loading="lazy" width="640" height="360">`:`<span class="art-category">${e(r.category_name||'资源收藏')}</span><span class="art-symbol">${icons[r.category_id||'']||'▧'}</span><span class="art-title">${e(r.title)}</span><span class="art-format">${e(r.format||'COLLECTION')}</span>`}${r.demo?'<span class="demo-tag">演示资料</span>':''}</a><div class="card-body"><div class="card-meta"><span>${e(r.category_name||'未分类')}</span><span>${e(r.format||'资料')}</span></div><h3><a href="/r/${e(r.id)}">${e(r.title)}</a></h3><p>${e(r.summary)}</p><div class="card-bottom"><div>${words.map(t=>`<span class="tag">${e(t)}</span>`).join('')}</div><span>${date(r.updated_at)}</span></div></div></article>`;
}
export function home(resources: Resource[], cats: Category[], total: number, query: string, category: string, page: number, provider: string) {
  const active = cats.find(x=>x.id===category);
  const filtered = !!(query || category || provider);
  const params = new URLSearchParams(); if(query)params.set('q',query);if(category)params.set('category',category);if(provider)params.set('provider',provider);
  return `<section class="search-home" aria-labelledby="search-title"><h1 id="search-title">资源搜索</h1><p>分享学习资料、办公模板、设计素材、软件工具和 AI 教程等夸克网盘资源，按需搜索，保存到自己的网盘。</p>
  <form class="search-bar" action="/" method="get" role="search"><span aria-hidden="true">⌕</span><input name="q" aria-label="搜索资源" placeholder="输入资源名称或关键词" value="${e(query)}" maxlength="100">${category?`<input type="hidden" name="category" value="${e(category)}">`:''}${provider?`<input type="hidden" name="provider" value="${e(provider)}">`:''}<button class="button primary">搜索资源</button></form><details class="search-settings"><summary>搜索设置</summary><fieldset><legend>本站没有结果时，搜索以下来源</legend>${searchSources.map(s=>`<label><input type="checkbox" data-search-source="${s.id}" checked> ${s.kind==='plugin'?'插件':'频道'} · ${e(s.label)}</label>`).join('')}<p>网络结果来自所选公开来源，仅展示夸克分享链接。</p></fieldset></details><p class="request-entry">没找到想要的？<a href="/request?${new URLSearchParams(query?{q:query}:{})}">提交资源需求 →</a></p></section>
  ${query?`<section class="resource-section home-resources"><div class="section-heading"><h2>${query?`“${e(query)}”的搜索结果`:active?e(active.name):'已有资源'}<span>${total}</span></h2><span class="muted">最新优先</span></div>${resources.length?`<div class="resource-list">${resources.map(r=>{const enabled=!!r.share_id&&!!r.share_url;return `<${enabled?'a':'article'} class="search-result${enabled?'':' unavailable'}" ${enabled?`href="/go/${e(r.share_id)}" target="_blank" rel="noopener noreferrer sponsored"`:''}><div class="search-result-top"><h3>${e(r.title)}</h3><time datetime="${e(r.updated_at)}">${e(new Date(r.updated_at).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}))}</time></div><div class="search-result-link"><span>${enabled?e(r.share_url):r.demo?'演示资料 · 暂无网盘链接':'链接暂不可用'}</span>${r.share_code?`<span class="result-code">提取码：${e(r.share_code)}</span>`:''}${enabled?'<span aria-hidden="true">↗</span>':''}</div></${enabled?'a':'article'}>`;}).join('')}</div>`:`<div id="network-results" data-query="${e(query)}"><p role="status">搜索中…</p><noscript>网络搜索需要启用 JavaScript。</noscript></div>`}
  ${total>12?`<nav class="pagination" aria-label="分页">${page>1?`<a class="button" href="/?${params}&page=${page-1}">上一页</a>`:''}<span>第 ${page} / ${Math.ceil(total/12)} 页</span>${page*12<total?`<a class="button" href="/?${params}&page=${page+1}">下一页</a>`:''}</nav>`:''}</section>`:''}`;
}
export function bodyHtml(text:string) {
  return text.split(/\n\s*\n/).map(p=>p.startsWith('## ')?`<h2>${e(p.slice(3))}</h2>`:p.split('\n').every(l=>l.startsWith('- '))?`<ul>${p.split('\n').map(l=>`<li>${e(l.slice(2))}</li>`).join('')}</ul>`:`<p>${e(p).replace(/\n/g,'<br>')}</p>`).join('');
}
export function detail(r:Resource, links:Link[], related:Resource[], channel:string, preview=false) {
  return `<nav class="breadcrumb"><a href="/">资源书架</a><span>/</span><a href="/?category=${e(r.category_id||'')}">${e(r.category_name||'未分类')}</a><span>/</span><span>资源详情</span></nav>${preview?'<div class="notice">这是管理员预览。草稿不会出现在公开页面中。</div>':''}${r.demo?'<div class="notice">这是一份演示资料，用来体验网站的分类与发布流程，尚未添加真实网盘链接。</div>':''}<div class="detail-layout"><article class="detail-article"><div class="detail-label">${e(r.category_name||'资源收藏')}</div><h1>${e(r.title)}</h1><p class="detail-summary">${e(r.summary)}</p><div class="detail-meta"><span>更新于 ${date(r.updated_at)}</span>${r.format?`<span>${e(r.format)}</span>`:''}${r.size?`<span>${e(r.size)}</span>`:''}</div>${r.cover_key?`<img class="detail-cover" src="/media/${e(r.cover_key)}" alt="${e(r.title)}">`:''}<div class="prose">${bodyHtml(r.body||'资源介绍正在整理。')}</div><div class="detail-tags">${r.tags.split(',').filter(Boolean).map(x=>`<a class="tag" href="/?q=${encodeURIComponent(x)}">${e(x)}</a>`).join('')}</div></article><aside class="download-panel"><span class="eyebrow">留一份，慢慢用</span><h2>获取这份资源</h2><p>选择网盘，打开后保存到自己的账号。</p>${links.length?links.map(l=>`<div class="download-item"><strong>${e(providers[l.provider]?.label||l.provider)}</strong>${l.code?`<div class="code-line"><span>提取码 <b>${e(l.code)}</b></span><button class="text-button" data-copy="${e(l.code)}">复制</button></div>`:''}${l.status==='active'&&!preview?`<a class="button primary full" href="/go/${e(l.id)}?from=${encodeURIComponent(channel)}" target="_blank" rel="noopener noreferrer sponsored">打开网盘 ↗</a>`:l.status==='disabled'?'<span class="disabled-link">链接维护中</span>':'<span class="disabled-link">预览模式不跳转网盘</span>'}</div>`).join(''):'<div class="download-empty">链接整理中<br><small>稍后回来看看</small></div>'}<div class="download-help"><a href="/about">第一次使用网盘？查看帮助</a></div><details class="report-details"><summary>链接失效？向我们反馈</summary><form data-report data-resource="${e(r.id)}"><label>遇到的问题<select name="reason"><option>链接失效</option><option>提取码错误</option><option>资源与描述不符</option><option>版权或其他问题</option></select></label><label>补充说明<textarea name="note" rows="3" maxlength="500" placeholder="哪个网盘链接有问题？"></textarea></label><label class="honeypot" aria-hidden="true">留空<input name="website" tabindex="-1" autocomplete="off"></label><button class="button full" ${preview?'disabled':''}>提交反馈</button></form></details></aside></div>${related.length?`<section class="resource-section"><div class="section-heading"><h2>也许你还需要</h2><a href="/?category=${e(r.category_id||'')}">查看同类资源 ↗</a></div><div class="resource-grid">${related.map(resourceCard).join('')}</div></section>`:''}`;
}
export function adminHeading(title:string,desc:string,action='') {return `<div class="admin-heading"><div><span class="eyebrow">资料室管理</span><h1>${title}</h1><p>${desc}</p></div>${action}</div>`;}
export function editor(r:Partial<Resource>,cats:Category[],links:Link[]) {
  return `${adminHeading(r.id?'编辑资源':'发布新资源','先保存草稿，确认内容后再发布。',r.id?`<a class="button" href="/admin/preview/${e(r.id)}" target="_blank">预览资源 ↗</a>`:'')}<form id="resource-form" data-id="${e(r.id||'')}"><div class="editor-grid"><section class="panel"><h2>资源内容</h2><label>资源标题 <span class="required">*</span><input name="title" required maxlength="120" value="${e(r.title||'')}" placeholder="清楚说明资源内容"></label><label>一句话介绍<textarea name="summary" rows="2" maxlength="300" placeholder="适合谁，能解决什么问题？">${e(r.summary||'')}</textarea></label><label>详细介绍<textarea class="body-editor" name="body" rows="15" maxlength="30000" placeholder="## 这份资源包含什么&#10;&#10;- 内容一&#10;- 内容二">${e(r.body||'')}</textarea><small>支持空行分段、以 ## 开头的小标题、以 - 开头的列表。正文按安全文本显示。</small></label><div class="form-pair"><label>文件格式<input name="format" maxlength="40" value="${e(r.format||'')}" placeholder="PDF / XLSX / ZIP"></label><label>资源大小<input name="size" maxlength="40" value="${e(r.size||'')}" placeholder="例如 12 MB"></label></div><label>关键词 / 标签<input name="tags" maxlength="300" value="${e(r.tags||'')}" placeholder="用逗号分隔，例如：简历,求职,模板"></label></section><div><section class="panel"><h2>整理与发布</h2><label>资源分类<select name="category_id"><option value="">未分类</option>${cats.map(c=>option(c.id,c.name,r.category_id||'')).join('')}</select></label><label>发布状态<select name="status">${option('draft','草稿 · 仅自己可见',r.status||'draft')}${option('published','发布 · 公开展示',r.status||'draft')}${option('archived','下架 · 暂停访问',r.status||'draft')}</select></label><label class="checkbox"><input type="checkbox" name="featured" ${r.featured?'checked':''}>设为精选资源</label><input type="hidden" name="cover_key" value=""></section><section class="panel"><div class="section-heading"><h2>网盘链接</h2><button type="button" class="text-button" id="add-link">＋ 添加</button></div><p class="muted">第一条为优先入口。仅填写你准备分享的链接。</p><div id="links-editor">${links.map(linkEditor).join('')}</div><template id="link-template">${linkEditor({id:'',provider:'quark',url:'',code:'',status:'active',position:0,resource_id:''})}</template></section></div></div><div class="save-bar"><span id="form-status" role="status">${r.id?'修改后记得保存':'新资源默认保存为草稿'}</span><a class="button" href="/admin">返回列表</a><button class="button primary" type="submit">保存资源</button></div></form>`;
}
function linkEditor(l:Link) {return `<fieldset class="link-row" data-id="${e(l.id)}"><legend>网盘入口</legend><div class="form-pair"><label>网盘<select data-field="provider">${Object.entries(providers).map(([k,v])=>option(k,v.label,l.provider)).join('')}</select></label><label>状态<select data-field="status">${option('active','可用',l.status)}${option('disabled','维护中',l.status)}</select></label></div><label>分享链接<input type="url" data-field="url" value="${e(l.url)}" placeholder="https://pan.quark.cn/s/…" required></label><div class="form-pair"><label>提取码<input data-field="code" value="${e(l.code)}" maxlength="30"></label><button type="button" class="text-button danger" data-remove-link>移除此入口</button></div></fieldset>`;}
